---
abstract: 'Wrapper for the hypothes.is web (HTTP) API.'
author:
  - 'Brandon E. Barker <brandon.barker@cornell.edu>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hypothesis-API
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/bbarker/Hypothesis-API.git
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
